

/*===================================================================================
* 
*   Copyright (c) Userware/OpenSilver.net
*      
*   This file is part of the OpenSilver Runtime (https://opensilver.net), which is
*   licensed under the MIT license: https://opensource.org/licenses/MIT
*   
*   As stated in the MIT license, "the above copyright notice and this permission
*   notice shall be included in all copies or substantial portions of the Software."
*  
\*====================================================================================*/


using CSHTML5.Internal;
using System;
using System.Collections.Generic;

#if MIGRATION
using System.Windows.Controls.Primitives;
#else
using Windows.UI.Xaml.Controls.Primitives;
#endif

#if MIGRATION
namespace System.Windows.Controls
#else
namespace Windows.UI.Xaml.Controls
#endif
{
    //------------
    // Note: unlike in .NET, we use the "ItemContainerGenerator" to store both the container (such as ListBoxItem or ComboBoxItem) AND the stuff generated by the DataTemplates.
    //------------

    public partial class ItemContainerGenerator
    {
        Dictionary<object, List<object>> _itemsToContainers = new Dictionary<object, List<object>>(); // Note: this maps each item (for example a string or a business object) to the corresponding element that is added to the visual tree (such a datatemplate) or to the native DOM element in case of native combo box for example. The reason why each single element can be associated to multiple objects is because of Strings and other value types: for example, if two identical strings are added to the ItemsControl, they will be the same key of the dictionary.
        private Dictionary<object, object> _containerToItem = new Dictionary<object, object>(); // This is the reverse of the line above. Used to resolve items from their containers.
        List<object> _containers = new List<object>(); //this list is kept to get the index from the container (with minimum work to keep it updated, it might not be the most efficient method perf-wise).

        /// <summary>
        /// Returns the container corresponding to the specified item.
        /// </summary>
        /// <param name="item">
        /// The item to retrieve the container for.
        /// </param>
        /// <returns>
        /// A container that corresponds to the specified item, if the item has a container
        /// and exists in the collection; otherwise, null.
        /// </returns>
        public DependencyObject ContainerFromItem(object item) //This signature is here to fit the original (Microsoft's) signature for this method.
        {
            return (DependencyObject)INTERNAL_ContainerFromItem(item);
        }

        public object INTERNAL_ContainerFromItem(object item) //Note: this signature is needed (at least) for the native ComboBox. The only difference is that we [do not need to]/[we cannot] cast the result into a DependencyObject
        {
            if (item != null && _itemsToContainers.ContainsKey(item))
            {
                List<object> containersAssociatedToTheItem = _itemsToContainers[item];
                if (containersAssociatedToTheItem != null && containersAssociatedToTheItem.Count > 0)
                {
                    return containersAssociatedToTheItem[0];
                }
                else
                    return null;
            }
            else
                return null;
        }

        /// <summary>
        /// Returns the container at the given index, or null if the index is negative or above the amount of containers.
        /// </summary>
        /// <param name="index">The index at which the container is located.</param>
        /// <returns>The container at the given index, or null if the index is negative or above the amount of containers.</returns>
        public DependencyObject ContainerFromIndex(int index)
        {
            if (index > -1 && _containers.Count > index)
            {
                return (DependencyObject)_containers[index];
            }
            else
                return null;
        }

        public int IndexFromContainer(DependencyObject container)
        {
            return _containers.IndexOf(container);
        }

        /// <summary>
        /// Removes the container associated to the item.
        /// </summary>
        /// <param name="container">The container to remove.</param>
        /// <param name="correspondingItem">The item that corresponds to the container to remove.</param>
        /// <returns>True if found and removed, false otherwise.</returns>
        public bool INTERNAL_TryUnregisterContainer(object container, object correspondingItem)
        {
            int indexOfContainerInContainerList = _containers.IndexOf(container);
            if (indexOfContainerInContainerList != -1)
            {
                _containers.Remove(container);
            }
            if (_itemsToContainers.ContainsKey(correspondingItem))
            {
                List<object> containersAssociatedToTheItem = _itemsToContainers[correspondingItem];
                if (containersAssociatedToTheItem != null)
                {
                    if (containersAssociatedToTheItem.Remove(container))
                    {

                        if (containersAssociatedToTheItem.Count == 0)
                            _itemsToContainers.Remove(correspondingItem);
                        
                        _containerToItem.Remove(container);

                        return true;
                    }
                }
            }

            return false;
        }

        ///// <summary>
        ///// Removes the container at the given position. IMPORTANT NOTE: Contrary to expectations, this method is not as efficient as INTERNAL_TryUnregisterContainer so if given the choice, use that one instead.
        ///// </summary>
        ///// <param name="index">The index of the Container to remove.</param>
        ///// <returns>True if found and removed, false otherwise</returns>
        //public bool INTERNAL_TryUnregisterContainerAt(int index)
        //{
        //    //Note: this method has not been tested yet.
        //    var container = ContainerFromIndex(index);
        //    foreach(object item in _itemsToContainers.Keys)
        //    {
        //        List<object> containersAssociatedToTheItem = _itemsToContainers[item];
        //        if (containersAssociatedToTheItem.Remove(container))
        //        {

        //            if (containersAssociatedToTheItem.Count == 0)
        //                _itemsToContainers.Remove(item);

        //            _containers.Remove(container);
        //            return true;
        //        }
        //    }
        //    return false;
        //}


        /// <summary>
        /// Resets the ItemContainerGenerator.
        /// </summary>
        public void INTERNAL_Clear()
        {
            _itemsToContainers.Clear();
            _containerToItem.Clear();
            _containers.Clear();
        }


        /// <summary>
        /// Adds a container to the collection of containers.
        /// </summary>
        /// <param name="container">The container to add.</param>
        /// <param name="correspondingItem">The item that corresponds to the container to add.</param>
        public void INTERNAL_RegisterContainer(object container, object correspondingItem)
        {
            List<object> containersAssociatedToTheItem;
            if (_itemsToContainers.ContainsKey(correspondingItem))
            {
                containersAssociatedToTheItem = _itemsToContainers[correspondingItem];
            }
            else
            {
                containersAssociatedToTheItem = new List<object>();
                _itemsToContainers.Add(correspondingItem, containersAssociatedToTheItem);
            }
            containersAssociatedToTheItem.Add(container);
            _containerToItem.Add(container, correspondingItem);
            _containers.Add(container);
        }

        /// <summary>
        /// Gets all the containers associated to all the items.
        /// </summary>
        public IEnumerable<object> INTERNAL_AllContainers
        {
            get
            {
                foreach (List<object> containers in
#if BRIDGE
                    INTERNAL_BridgeWorkarounds.GetDictionaryValues_SimulatorCompatible(_itemsToContainers)
#else
                    _itemsToContainers.Values
#endif

                    )
                {
                    foreach (object container in containers)
                    {
                        yield return container;
                    }
                }
            }
        }

        /// <summary>
        /// Returns the item that corresponds to the specified, generated container.
        /// </summary>
        /// <param name="container">
        /// The <see cref="DependencyObject"/> that corresponds to the item to be returned.
        /// </param>
        /// <returns>
        /// The contained item, or the container if it does not contain an item.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// container is null.
        /// </exception>
        public object ItemFromContainer(DependencyObject container)
        {
            if (container == null)
            {
                throw new ArgumentNullException("container");
            }
            if (_containerToItem.ContainsKey(container))
            {
                return _containerToItem[container];
            }

            return DependencyProperty.UnsetValue;
        }

#if WORKINPROGRESS
        //
        // Summary:
        //     Occurs when the contents of the items collection changes.
        [OpenSilver.NotImplemented]
        public event ItemsChangedEventHandler ItemsChanged;

        //
        // Summary:
        //     Gets the generated position of the item at the specified index.
        //
        // Parameters:
        //   itemIndex:
        //     The index of the item to retrieve the position of.
        //
        // Returns:
        //     The position of the item as generated by the System.Windows.Controls.ItemContainerGenerator.
        [OpenSilver.NotImplemented]
        public GeneratorPosition GeneratorPositionFromIndex(int itemIndex)
        {
            return new GeneratorPosition();
        }
        //
        // Summary:
        //     Returns the index that maps to the specified System.Windows.Controls.Primitives.GeneratorPosition.
        //
        // Parameters:
        //   position:
        //     The System.Windows.Controls.Primitives.GeneratorPosition for the desired index.
        //
        // Returns:
        //     An System.Int32 that is the index which maps to the specified System.Windows.Controls.Primitives.GeneratorPosition.
        [OpenSilver.NotImplemented]
        public int IndexFromGeneratorPosition(GeneratorPosition position)
        {
            return 0;
        }

#endif
    }
}

