//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSilver.Internal.Interactivity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionStringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Interactivity.ExceptionStringTable", typeof(ExceptionStringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the same BehaviorCollection on multiple objects..
        /// </summary>
        internal static string CannotHostBehaviorCollectionMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostBehaviorCollectionMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of a Behavior cannot be attached to more than one object at a time..
        /// </summary>
        internal static string CannotHostBehaviorMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostBehaviorMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot host an instance of a TriggerAction in multiple TriggerCollections simultaneously. Remove it from one TriggerCollection before adding it to another..
        /// </summary>
        internal static string CannotHostTriggerActionMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostTriggerActionMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the same TriggerCollection on multiple objects..
        /// </summary>
        internal static string CannotHostTriggerCollectionMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostTriggerCollectionMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of a trigger cannot be attached to more than one object at a time..
        /// </summary>
        internal static string CannotHostTriggerMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostTriggerMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &quot;{0}&quot; does not exist or is not publicly exposed on {1}..
        /// </summary>
        internal static string CommandDoesNotExistOnBehaviorWarningMessage {
            get {
                return ResourceManager.GetString("CommandDoesNotExistOnBehaviorWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid type for the TriggerType parameter. Make sure &quot;{0}&quot; derives from TriggerBase..
        /// </summary>
        internal static string DefaultTriggerAttributeInvalidTriggerTypeSpecifiedExceptionMessage {
            get {
                return ResourceManager.GetString("DefaultTriggerAttributeInvalidTriggerTypeSpecifiedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add the same instance of &quot;{0}&quot; to a &quot;{1}&quot; more than once..
        /// </summary>
        internal static string DuplicateItemInCollectionExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateItemInCollectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event &quot;{0}&quot; on type &quot;{1}&quot; has an incompatible signature. Make sure the event is public and satisfies the EventHandler delegate..
        /// </summary>
        internal static string EventTriggerBaseInvalidEventExceptionMessage {
            get {
                return ResourceManager.GetString("EventTriggerBaseInvalidEventExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an event named &quot;{0}&quot; on type &quot;{1}&quot;..
        /// </summary>
        internal static string EventTriggerCannotFindEventNameExceptionMessage {
            get {
                return ResourceManager.GetString("EventTriggerCannotFindEventNameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type &quot;{0}&quot; cannot have a {3} property of type &quot;{1}&quot;. Instances of type &quot;{0}&quot; can have only a {3} property of type &quot;{2}&quot;..
        /// </summary>
        internal static string RetargetedTypeConstraintViolatedExceptionMessage {
            get {
                return ResourceManager.GetString("RetargetedTypeConstraintViolatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot attach type &quot;{0}&quot; to type &quot;{1}&quot;. Instances of type &quot;{0}&quot; can only be attached to objects of type &quot;{2}&quot;..
        /// </summary>
        internal static string TypeConstraintViolatedExceptionMessage {
            get {
                return ResourceManager.GetString("TypeConstraintViolatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve TargetName &quot;{0}&quot;..
        /// </summary>
        internal static string UnableToResolveTargetNameWarningMessage {
            get {
                return ResourceManager.GetString("UnableToResolveTargetNameWarningMessage", resourceCulture);
            }
        }
    }
}
