<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>
    <OpenSilverGenerateAssemblyInfo>true</OpenSilverGenerateAssemblyInfo>
    <OpenSilverExposeResourcesToExtractor>false</OpenSilverExposeResourcesToExtractor>
    <OpenSilverXamlPreprocessorOptions>optimize</OpenSilverXamlPreprocessorOptions>
    <EnableAdditionalMetadataAttributes>true</EnableAdditionalMetadataAttributes>
  </PropertyGroup>
</Project>