//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSilver.Internal.Navigation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Navigation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go back when {0} is false..
        /// </summary>
        internal static string CannotGoBack {
            get {
                return ResourceManager.GetString("CannotGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go forward when {0} is false..
        /// </summary>
        internal static string CannotGoForward {
            get {
                return ResourceManager.GetString("CannotGoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to zero..
        /// </summary>
        internal static string Frame_CacheSizeMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Frame_CacheSizeMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set {0} during a load operation..
        /// </summary>
        internal static string Frame_CannotSetLoaderWhenLoading {
            get {
                return ResourceManager.GetString("Frame_CannotSetLoaderWhenLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string Frame_DefaultContent {
            get {
                return ResourceManager.GetString("Frame_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content for the URI cannot be loaded. The URI may be invalid..
        /// </summary>
        internal static string NavigationService_CannotLoadUri {
            get {
                return ResourceManager.GetString("NavigationService_CannotLoadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content loaded was of type {0}, which is not a subclass of {1}..
        /// </summary>
        internal static string NavigationService_ContentIsNotAUserControl {
            get {
                return ResourceManager.GetString("NavigationService_ContentIsNotAUserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation to a fragment requires the {0} to have content currently..
        /// </summary>
        internal static string NavigationService_FragmentNavigationRequiresContent {
            get {
                return ResourceManager.GetString("NavigationService_FragmentNavigationRequiresContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} returned by the {1}..
        /// </summary>
        internal static string NavigationService_InvalidLoadResult {
            get {
                return ResourceManager.GetString("NavigationService_InvalidLoadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be set to {1} if this is a top-level {2}..
        /// </summary>
        internal static string NavigationService_JournalOwnership_UsesParentJournal_OnlyTopLevel {
            get {
                return ResourceManager.GetString("NavigationService_JournalOwnership_UsesParentJournal_OnlyTopLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation to a null URI is not supported..
        /// </summary>
        internal static string NavigationService_NavigationToANullUriIsNotSupported {
            get {
                return ResourceManager.GetString("NavigationService_NavigationToANullUriIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to load local XAML with an invalid syntax.  When a &apos;;component/&apos; is present, it must have the assembly name on the left side, and the page path and name on the right..
        /// </summary>
        internal static string PageResourceContentLoader_InvalidComponentSyntax {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_InvalidComponentSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML was found at the location &apos;{0}&apos;..
        /// </summary>
        internal static string PageResourceContentLoader_NoXAMLWasFound {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_NoXAMLWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos;, specified in the x:Class of &apos;{1}&apos; could not be found in any loaded assembly..
        /// </summary>
        internal static string PageResourceContentLoader_TheTypeSpecifiedInTheXClassCouldNotBeFound {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_TheTypeSpecifiedInTheXClassCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong kind of {0} passed in.  The {0} passed in should only come from {1}..
        /// </summary>
        internal static string PageResourceContentLoader_WrongIAsyncResult {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_WrongIAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML at location &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string PageResourceContentLoader_XAMLWasUnloadable {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_XAMLWasUnloadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set because the underlying property is read only..
        /// </summary>
        internal static string UnderlyingPropertyIsReadOnly {
            get {
                return ResourceManager.GetString("UnderlyingPropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not have a null {1}..
        /// </summary>
        internal static string UriMapper_MustNotHaveANullUriMappingCollection {
            get {
                return ResourceManager.GetString("UriMapper_MustNotHaveANullUriMappingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be a URI fragment (cannot begin with &apos;#&apos;)..
        /// </summary>
        internal static string UriMapping_MappedUriCannotBeOnlyFragment {
            get {
                return ResourceManager.GetString("UriMapping_MappedUriCannotBeOnlyFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be only a query string..
        /// </summary>
        internal static string UriMapping_MappedUriCannotBeOnlyQueryString {
            get {
                return ResourceManager.GetString("UriMapping_MappedUriCannotBeOnlyQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} template must be specified..
        /// </summary>
        internal static string UriMapping_TemplateMustBeSpecified {
            get {
                return ResourceManager.GetString("UriMapping_TemplateMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} template cannot contain the same identifier more than once..
        /// </summary>
        internal static string UriMapping_UriTemplateCannotContainTheSameIdentifierMoreThanOnce {
            get {
                return ResourceManager.GetString("UriMapping_UriTemplateCannotContainTheSameIdentifierMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} template cannot have a fragment..
        /// </summary>
        internal static string UriMapping_UriTemplateCannotHaveAFragment {
            get {
                return ResourceManager.GetString("UriMapping_UriTemplateCannotHaveAFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} template cannot have a query string..
        /// </summary>
        internal static string UriMapping_UriTemplateCannotHaveAQueryString {
            get {
                return ResourceManager.GetString("UriMapping_UriTemplateCannotHaveAQueryString", resourceCulture);
            }
        }
    }
}
