
/*===================================================================================
* 
*   Copyright (c) Userware (OpenSilver.net, CSHTML5.com)
*      
*   This file is part of both the OpenSilver Compiler (https://opensilver.net), which
*   is licensed under the MIT license (https://opensource.org/licenses/MIT), and the
*   CSHTML5 Compiler (http://cshtml5.com), which is dual-licensed (MIT + commercial).
*   
*   As stated in the MIT license, "the above copyright notice and this permission
*   notice shall be included in all copies or substantial portions of the Software."
*  
\*====================================================================================*/

using Mono.Cecil;
using System.Linq;
using System.Xml;
using System.Xml.Linq;

namespace OpenSilver.Compiler;

internal static class InsertingMarkupNodesInXaml
{
    public static readonly XName GeneratedMarkupExtensionAttribute = GeneratingCode.xNamespace.GetName("__.GeneratedMarkupExtension.__");

    internal static void InsertMarkupNodes(XDocument doc, ConversionSettings settings) => TraverseNextElement(doc.Root, settings);

    private static void TraverseNextElement(XElement element, ConversionSettings settings)
    {
        // Recurse immediately to avoid processing elements generated by this step.
        foreach (var child in element.Elements())
        {
            TraverseNextElement(child, settings);
        }

        if (XamlParser.IsMemberNode(element))
        {
            return;
        }

        // We use a secondary list so that when we remove an element from the XAttributes, we don't skip the next element.
        // We reverse the list because we want to preserve the order in which we set the object properties. Since XContainer
        // only allow to add a child at the start or the end, we need call XContainer.AddFirst(element) while iterating on the 
        // reverse list of attributes to do so.
        var attributes = element.Attributes().ToArray();

        for (int i = attributes.Length - 1; i >= 0; i--)
        {
            XAttribute attribute = attributes[i];

            if (GeneratingCode.SkipAttribute(attribute))
            {
                continue;
            }

            if (!MarkupExtensionDescriptor.IsMarkupExtension(attribute.Value))
            {
                continue;
            }

            if (GeneratingCode.IsXNameAttribute(attribute) || GeneratingCode.IsNameAttribute(attribute))
            {
                throw new XamlParseException(
                    $"MarkupExtensions are not allowed for Name property values, so '{attribute}' is not valid.",
                    attribute);
            }

            var descriptor = MarkupExtensionDescriptor.Parse(attribute.Value, attribute);

            XName memberName;
            int index = attribute.Name.LocalName.IndexOf('.');

            if (index == -1)
            {
                memberName = element.Name.Namespace.GetName($"{element.Name.LocalName}.{attribute.Name.LocalName}");
            }
            else
            {
                XNamespace xmlns = attribute.Name.Namespace == XNamespace.None ?
                    element.GetDefaultNamespace() :
                    attribute.Name.Namespace;

                memberName = xmlns.GetName(attribute.Name.LocalName);
            }

            element.AddFirst(
                GenerateMemberNode(memberName, descriptor, settings, element, attribute));

            attribute.Remove();
        }
    }

    private static XElement GenerateMemberNode(
        XName memberName,
        MarkupExtensionDescriptor descriptor,
        ConversionSettings settings,
        XElement xmlnsResolver,
        IXmlLineInfo lineInfo)
    {
        XElement extensionElement = GenerateExtensionElement(descriptor, settings, xmlnsResolver, lineInfo);

        var wrapper = new ExtendedXElement(
            memberName,
            extensionElement);
        wrapper.SetLineInfo(lineInfo);

        return wrapper;
    }

    internal static XElement GenerateExtensionElement(
        MarkupExtensionDescriptor descriptor,
        ConversionSettings settings,
        XElement xmlnsResolver,
        IXmlLineInfo lineInfo)
    {
        TypeDefinition markupExtensionType =
            GeneratingCode.GetTypeDefinitionFromString($"{descriptor.Name}Extension", xmlnsResolver, lineInfo, settings, false) ??
            GeneratingCode.GetTypeDefinitionFromString(descriptor.Name, xmlnsResolver, lineInfo, settings, true);

        var markupExtensionElement = new ExtendedXElement(
            ResolveNamespace(descriptor.Name, xmlnsResolver).GetName(markupExtensionType.Name));
        markupExtensionElement.SetAttributeValue(GeneratedMarkupExtensionAttribute, "True");
        markupExtensionElement.SetLineInfo(lineInfo);

        if (descriptor.ContentProperty is not null)
        {
            string contentPropertyName = ResolveContentPropertyName(markupExtensionType, settings, lineInfo);

            AddProperty(markupExtensionElement, contentPropertyName, descriptor.ContentProperty, settings, xmlnsResolver, lineInfo);
        }

        foreach (var (propName, propValue) in descriptor.Properties)
        {
            AddProperty(markupExtensionElement, propName, propValue, settings, xmlnsResolver, lineInfo);
        }
        
        return markupExtensionElement;
    }

    private static void AddProperty(
        XElement element,
        string propertyName,
        object value,
        ConversionSettings settings,
        XElement xmlnsResolver,
        IXmlLineInfo lineInfo)
    {
        if (value is MarkupExtensionDescriptor nestedDescriptor)
        {
            element.Add(
                GenerateMemberNode(
                    ResolveMemberName(element, propertyName, xmlnsResolver),
                    nestedDescriptor,
                    settings,
                    xmlnsResolver,
                    lineInfo));
        }
        else
        {
            var attribute = new ExtendedXAttribute(propertyName, value);
            attribute.SetLineInfo(lineInfo);

            element.Add(attribute);
        }
    }

    private static string ResolveContentPropertyName(
        TypeDefinition type,
        ConversionSettings settings,
        IXmlLineInfo lineInfo)
    {
        string contentPropertyName = settings.Inspector.GetContentPropertyName(type, lineInfo);

        if (string.IsNullOrEmpty(contentPropertyName))
        {
            throw new XamlParseException(
                $"Cannot add content to object of type '{settings.TypeReferenceHelper.ConvertToString(type)}'.",
                lineInfo);
        }

        return contentPropertyName;
    }

    private static XName ResolveMemberName(XElement extensionElement, string propertyName, XElement xmlnsResolver)
    {
        int dotIndex = propertyName.IndexOf('.');
        if (dotIndex == -1)
        {
            return extensionElement.Name.Namespace.GetName(
                $"{extensionElement.Name.LocalName}.{propertyName}");
        }

        int colonIndex = propertyName.IndexOf(':');
        string localName = colonIndex == -1 ? propertyName : propertyName.Substring(colonIndex + 1);
        XNamespace ns = ResolveNamespace(propertyName, xmlnsResolver);
        return ns.GetName(localName);
    }

    private static XNamespace ResolveNamespace(string value, XElement xmlnsResolver)
    {
        int index = value.IndexOf(':');

        if (index == -1)
        {
            return xmlnsResolver.GetDefaultNamespace();
        }
        else
        {
            string prefix = value.Substring(0, index);
            return xmlnsResolver.GetNamespaceOfPrefix(prefix);
        }
    }
}
