
//===============================================================================
//
//  IMPORTANT NOTICE, PLEASE READ CAREFULLY:
//
//  => This code is licensed under the GNU General Public License (GPL v3). A copy of the license is available at:
//        https://www.gnu.org/licenses/gpl.txt
//
//  => As stated in the license text linked above, "The GNU General Public License does not permit incorporating your program into proprietary programs". It also does not permit incorporating this code into non-GPL-licensed code (such as MIT-licensed code) in such a way that results in a non-GPL-licensed work (please refer to the license text for the precise terms).
//
//  => Licenses that permit proprietary use are available at:
//        http://www.cshtml5.com
//
//  => Copyright 2019 Userware/CSHTML5. This code is part of the CSHTML5 product (cshtml5.com).
//
//===============================================================================



using System;

namespace System.Xml.Serialization
{
    /// <summary>
    /// Signifies that the code was generated by the serialization infrastructure
    /// and can be reused for increased performance, when this attribute is applied
    /// to an assembly.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly)]
    public sealed class XmlSerializerVersionAttribute : Attribute
    {
        // Summary:
        //     
        //     
        /// <summary>
        /// Initializes a new instance of the System.Xml.Serialization.XmlSerializerVersionAttribute
        /// class.
        /// </summary>
        public XmlSerializerVersionAttribute()
        {
        }
     
        /// <summary>
        /// Initializes a new instance of the System.Xml.Serialization.XmlSerializerVersionAttribute
        /// class for the specified type.
        /// </summary>
        /// <param name="type">The type that is being serialized.</param>
        public XmlSerializerVersionAttribute(Type type)
        {
        }

        /// <summary>
        /// Gets or sets the common language runtime (CLR) namespace of the assembly.
        /// </summary>
        public string Namespace { get; set; }
       
        /// <summary>
        /// Gets or sets the identity of the parent assembly.
        /// </summary>
        public string ParentAssemblyId { get; set; }
      
        /// <summary>
        /// Gets or sets the type that the serializer operates on.
        /// </summary>
        public Type Type { get; set; }
      
        /// <summary>
        /// Gets or sets the assembly's version number.
        /// </summary>
        public string Version { get; set; }
    }
}
