
//===============================================================================
//
//  IMPORTANT NOTICE, PLEASE READ CAREFULLY:
//
//  ● This code is dual-licensed (GPLv3 + Commercial). Commercial licenses can be obtained from: http://cshtml5.com
//
//  ● You are NOT allowed to:
//       – Use this code in a proprietary or closed-source project (unless you have obtained a commercial license)
//       – Mix this code with non-GPL-licensed code (such as MIT-licensed code), or distribute it under a different license
//       – Remove or modify this notice
//
//  ● Copyright 2019 Userware/CSHTML5. This code is part of the CSHTML5 product.
//
//===============================================================================


using System;

namespace System.Xml.Serialization
{
    /// <summary>
    /// Signifies that the code was generated by the serialization infrastructure
    /// and can be reused for increased performance, when this attribute is applied
    /// to an assembly.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly)]
    public sealed class XmlSerializerVersionAttribute : Attribute
    {
        // Summary:
        //     
        //     
        /// <summary>
        /// Initializes a new instance of the System.Xml.Serialization.XmlSerializerVersionAttribute
        /// class.
        /// </summary>
        public XmlSerializerVersionAttribute()
        {
        }
     
        /// <summary>
        /// Initializes a new instance of the System.Xml.Serialization.XmlSerializerVersionAttribute
        /// class for the specified type.
        /// </summary>
        /// <param name="type">The type that is being serialized.</param>
        public XmlSerializerVersionAttribute(Type type)
        {
        }

        /// <summary>
        /// Gets or sets the common language runtime (CLR) namespace of the assembly.
        /// </summary>
        public string Namespace { get; set; }
       
        /// <summary>
        /// Gets or sets the identity of the parent assembly.
        /// </summary>
        public string ParentAssemblyId { get; set; }
      
        /// <summary>
        /// Gets or sets the type that the serializer operates on.
        /// </summary>
        public Type Type { get; set; }
      
        /// <summary>
        /// Gets or sets the assembly's version number.
        /// </summary>
        public string Version { get; set; }
    }
}
