//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSilver.Controls.Input.Toolkit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtime.OpenSilver.Controls.Input.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation..
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index value &apos;{0}&apos;.
        /// </summary>
        internal static string DomainUpDown_CurrentIndex_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_CurrentIndex_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InvalidInputAction value &apos;{0}&apos;.
        /// </summary>
        internal static string DomainUpDown_InvalidInputAction_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_InvalidInputAction_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to change read-only property &quot;{0}.&quot;.
        /// </summary>
        internal static string InvalidAttemptToChangeReadOnlyProperty {
            get {
                return ResourceManager.GetString("InvalidAttemptToChangeReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property TimeItemsSelection..
        /// </summary>
        internal static string ListTimePickerPopup_TimeItemsSelection_ReadOnly {
            get {
                return ResourceManager.GetString("ListTimePickerPopup_TimeItemsSelection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid double value &apos;{0}&apos;: valid value is of double type and within decimal range..
        /// </summary>
        internal static string NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Increment value &apos;{0}&apos;: valid value is of double type, within decimal range, and positive.
        /// </summary>
        internal static string NumericUpDown_EnsureValidIncrementValue_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidIncrementValue_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DecimalPlaces value &apos;{0}&apos;: valid value is of int type and within 0 and 15 inclusive..
        /// </summary>
        internal static string NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is currently ReadOnly and should not be modified..
        /// </summary>
        internal static string ObservableObjectCollection_ReadOnly {
            get {
                return ResourceManager.GetString("ObservableObjectCollection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero..
        /// </summary>
        internal static string Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupButtonMode value &apos;{0}&apos;..
        /// </summary>
        internal static string Picker_PopupButtonModeNotValid {
            get {
                return ResourceManager.GetString("Picker_PopupButtonModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be larger than or equal to 0..
        /// </summary>
        internal static string Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string RatingAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null or a number between 0 and 1..
        /// </summary>
        internal static string RatingAutomationPeer_SetValue {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string RatingItemAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingItemAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin action is not valid at this moment..
        /// </summary>
        internal static string Spinner_SpinNotValid {
            get {
                return ResourceManager.GetString("Spinner_SpinNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupMinutesInterval &apos;{0}&apos;. The interval can be set to 0 (no interval) to and including 59..
        /// </summary>
        internal static string TimeInput_PopupMinutesInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupMinutesInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupSecondsInterval &apos;{0}&apos;.The interval can be set to 0 (no interval) to and including 59..
        /// </summary>
        internal static string TimeInput_PopupSecondsInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupSecondsInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the PopupProperty in a style. Please use PopupTemplate..
        /// </summary>
        internal static string TimePicker_PopupSetInStyle {
            get {
                return ResourceManager.GetString("TimePicker_PopupSetInStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupTimeSelectionMode for this popup, value &apos;{0}&apos;..
        /// </summary>
        internal static string TimePicker_PopupTimeSelectionModeNotValid {
            get {
                return ResourceManager.GetString("TimePicker_PopupTimeSelectionModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property TimeHintContent..
        /// </summary>
        internal static string TimeUpDown_OnTimeHintContentChanged {
            get {
                return ResourceManager.GetString("TimeUpDown_OnTimeHintContentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot convert from &apos;{1}&apos;..
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse text &apos;{0}&apos;.
        /// </summary>
        internal static string UpDown_ParseException {
            get {
                return ResourceManager.GetString("UpDown_ParseException", resourceCulture);
            }
        }
    }
}
