
//===============================================================================
//
//  IMPORTANT NOTICE, PLEASE READ CAREFULLY:
//
//  ● This code is dual-licensed (GPLv3 + Commercial). Commercial licenses can be obtained from: http://cshtml5.com
//
//  ● You are NOT allowed to:
//       – Use this code in a proprietary or closed-source project (unless you have obtained a commercial license)
//       – Mix this code with non-GPL-licensed code (such as MIT-licensed code), or distribute it under a different license
//       – Remove or modify this notice
//
//  ● Copyright 2019 Userware/CSHTML5. This code is part of the CSHTML5 product.
//
//===============================================================================


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace System.CodeDom.Compiler
{
    /// <summary>
    /// Identifies code generated by a tool. This class cannot be inherited.
    /// </summary>
    [AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
    public sealed class GeneratedCodeAttribute : Attribute
    {
        
        /// <summary>
        /// Initializes a new instance of the System.CodeDom.Compiler.GeneratedCodeAttribute
        /// class specifying the name and version of the tool that generated the code.
        /// </summary>
        /// <param name="tool">The name of the tool that generated the code.</param>
        /// <param name="version">The version of the tool that generated the code.</param>
        public GeneratedCodeAttribute(string tool, string version)
        {
            Tool = tool;
            Version = version;
        }

        /// <summary>
        /// Gets the name of the tool that generated the code.
        /// </summary>
        public string Tool { get; private set; }

        /// <summary>
        /// Gets the version of the tool that generated the code.
        /// </summary>
        public string Version { get; private set; }
    }
}
