
//===============================================================================
//
//  IMPORTANT NOTICE, PLEASE READ CAREFULLY:
//
//  => This code is licensed under the GNU General Public License (GPL v3). A copy of the license is available at:
//        https://www.gnu.org/licenses/gpl.txt
//
//  => As stated in the license text linked above, "The GNU General Public License does not permit incorporating your program into proprietary programs". It also does not permit incorporating this code into non-GPL-licensed code (such as MIT-licensed code) in such a way that results in a non-GPL-licensed work (please refer to the license text for the precise terms).
//
//  => Licenses that permit proprietary use are available at:
//        http://www.cshtml5.com
//
//  => Copyright 2019 Userware/CSHTML5. This code is part of the CSHTML5 product (cshtml5.com).
//
//===============================================================================



using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace System.CodeDom.Compiler
{
    /// <summary>
    /// Identifies code generated by a tool. This class cannot be inherited.
    /// </summary>
    [AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
    public sealed partial class GeneratedCodeAttribute : Attribute
    {
        
        /// <summary>
        /// Initializes a new instance of the System.CodeDom.Compiler.GeneratedCodeAttribute
        /// class specifying the name and version of the tool that generated the code.
        /// </summary>
        /// <param name="tool">The name of the tool that generated the code.</param>
        /// <param name="version">The version of the tool that generated the code.</param>
        public GeneratedCodeAttribute(string tool, string version)
        {
            Tool = tool;
            Version = version;
        }

        /// <summary>
        /// Gets the name of the tool that generated the code.
        /// </summary>
        public string Tool { get; private set; }

        /// <summary>
        /// Gets the version of the tool that generated the code.
        /// </summary>
        public string Version { get; private set; }
    }
}
