//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if MIGRATION
namespace System.Windows.Controls
#else
namespace Windows.UI.Xaml.Controls
#endif
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column collection cannot be changed while adjusting display indexes..
        /// </summary>
        internal static string DataGrid_CannotChangeColumnCollectionWhileAdjustingDisplayIndexes {
            get {
                return ResourceManager.GetString("DataGrid_CannotChangeColumnCollectionWhileAdjustingDisplayIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items cannot be added, removed or reset while rows are loading or unloading..
        /// </summary>
        internal static string DataGrid_CannotChangeItemsWhenLoadingRows {
            get {
                return ResourceManager.GetString("DataGrid_CannotChangeItemsWhenLoadingRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column cannot be collapsed..
        /// </summary>
        internal static string DataGrid_ColumnCannotBeCollapsed {
            get {
                return ResourceManager.GetString("DataGrid_ColumnCannotBeCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column already belongs to a DataGrid instance and cannot be reassigned..
        /// </summary>
        internal static string DataGrid_ColumnCannotBeReassignedToDifferentDataGrid {
            get {
                return ResourceManager.GetString("DataGrid_ColumnCannotBeReassignedToDifferentDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided column does not belong to this DataGrid..
        /// </summary>
        internal static string DataGrid_ColumnNotInThisDataGrid {
            get {
                return ResourceManager.GetString("DataGrid_ColumnNotInThisDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not contained in the ItemsSource..
        /// </summary>
        internal static string DataGrid_ItemIsNotContainedInTheItemsSource {
            get {
                return ResourceManager.GetString("DataGrid_ItemIsNotContainedInTheItemsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current row.  Operation cannot be completed..
        /// </summary>
        internal static string DataGrid_NoCurrentRow {
            get {
                return ResourceManager.GetString("DataGrid_NoCurrentRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no instance of DataGrid assigned to this {0}.  Operation cannot be completed..
        /// </summary>
        internal static string DataGrid_NoOwningGrid {
            get {
                return ResourceManager.GetString("DataGrid_NoOwningGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set because the underlying property is read only..
        /// </summary>
        internal static string DataGrid_UnderlyingPropertyIsReadOnly {
            get {
                return ResourceManager.GetString("DataGrid_UnderlyingPropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set to infinity..
        /// </summary>
        internal static string DataGrid_ValueCannotBeSetToInfinity {
            get {
                return ResourceManager.GetString("DataGrid_ValueCannotBeSetToInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set to double.NAN..
        /// </summary>
        internal static string DataGrid_ValueCannotBeSetToNAN {
            get {
                return ResourceManager.GetString("DataGrid_ValueCannotBeSetToNAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set to a null value..
        /// </summary>
        internal static string DataGrid_ValueCannotBeSetToNull {
            get {
                return ResourceManager.GetString("DataGrid_ValueCannotBeSetToNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not an instance of {0}..
        /// </summary>
        internal static string DataGrid_ValueIsNotAnInstanceOf {
            get {
                return ResourceManager.GetString("DataGrid_ValueIsNotAnInstanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not an instance of {0} or {1}..
        /// </summary>
        internal static string DataGrid_ValueIsNotAnInstanceOfEitherOr {
            get {
                return ResourceManager.GetString("DataGrid_ValueIsNotAnInstanceOfEitherOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string DataGrid_ValueMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("DataGrid_ValueMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1} and less than {2}..
        /// </summary>
        internal static string DataGrid_ValueMustBeGTandLT {
            get {
                return ResourceManager.GetString("DataGrid_ValueMustBeGTandLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1} and less than or equal to {2}..
        /// </summary>
        internal static string DataGrid_ValueMustBeGTandLTE {
            get {
                return ResourceManager.GetString("DataGrid_ValueMustBeGTandLTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1} and less than {2}..
        /// </summary>
        internal static string DataGrid_ValueMustBeGTEandLT {
            get {
                return ResourceManager.GetString("DataGrid_ValueMustBeGTEandLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1} and less than or equal to {2}..
        /// </summary>
        internal static string DataGrid_ValueMustBeGTEandLTE {
            get {
                return ResourceManager.GetString("DataGrid_ValueMustBeGTEandLTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        internal static string DataGrid_ValueMustBeLessThan {
            get {
                return ResourceManager.GetString("DataGrid_ValueMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        internal static string DataGrid_ValueMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("DataGrid_ValueMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the operation..
        /// </summary>
        internal static string DataGridAutomationPeer_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("DataGridAutomationPeer_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content does not support UIElement; use ContentTemplate instead..
        /// </summary>
        internal static string DataGridColumnHeader_ContentDoesNotSupportUIElements {
            get {
                return ResourceManager.GetString("DataGridColumnHeader_ContentDoesNotSupportUIElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ascending.
        /// </summary>
        internal static string DataGridColumnHeaderAutomationPeer_Ascending {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderAutomationPeer_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descending.
        /// </summary>
        internal static string DataGridColumnHeaderAutomationPeer_Descending {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderAutomationPeer_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid DataGridLengthUnitType..
        /// </summary>
        internal static string DataGridLength_InvalidUnitType {
            get {
                return ResourceManager.GetString("DataGridLength_InvalidUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGridLengthConverter cannot convert from {0}..
        /// </summary>
        internal static string DataGridLengthConverter_CannotConvertFrom {
            get {
                return ResourceManager.GetString("DataGridLengthConverter_CannotConvertFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from DataGridLength to {0}..
        /// </summary>
        internal static string DataGridLengthConverter_CannotConvertTo {
            get {
                return ResourceManager.GetString("DataGridLengthConverter_CannotConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DataGridLength..
        /// </summary>
        internal static string DataGridLengthConverter_InvalidDataGridLength {
            get {
                return ResourceManager.GetString("DataGridLengthConverter_InvalidDataGridLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid row index. Operation cannot be completed..
        /// </summary>
        internal static string DataGridRow_InvalidRowIndexCannotCompleteOperation {
            get {
                return ResourceManager.GetString("DataGridRow_InvalidRowIndexCannotCompleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} items).
        /// </summary>
        internal static string DataGridRowGroupHeader_ItemCountPlural {
            get {
                return ResourceManager.GetString("DataGridRowGroupHeader_ItemCountPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} item).
        /// </summary>
        internal static string DataGridRowGroupHeader_ItemCountSingular {
            get {
                return ResourceManager.GetString("DataGridRowGroupHeader_ItemCountSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        internal static string DataGridRowGroupHeader_PropertyName {
            get {
                return ResourceManager.GetString("DataGridRowGroupHeader_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only change SelectedItems collection in Extended selection mode.  Use SelectedItem property in Single selection mode..
        /// </summary>
        internal static string DataGridSelectedItemsCollection_CannotChangeSelectedItemsCollectionInSingleMode {
            get {
                return ResourceManager.GetString("DataGridSelectedItemsCollection_CannotChangeSelectedItemsCollectionInSingleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing template.  Cannot initialize {0}..
        /// </summary>
        internal static string DataGridTemplateColumn_MissingTemplateForType {
            get {
                return ResourceManager.GetString("DataGridTemplateColumn_MissingTemplateForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; ({1}) is invalid for Enum type &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidEnumArgumentException_InvalidEnumArgument {
            get {
                return ResourceManager.GetString("InvalidEnumArgumentException_InvalidEnumArgument", resourceCulture);
            }
        }
    }
}
