//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace TestApplication.LegacyBasicHttpServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="LegacyBasicHttpServiceReference.BasicHttpService")]
    public interface BasicHttpService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:BasicHttpService/Echo", ReplyAction="urn:BasicHttpService/EchoResponse")]
        System.IAsyncResult BeginEcho(string message, System.AsyncCallback callback, object asyncState);
        
        string EndEcho(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:BasicHttpService/BodyMember", ReplyAction="urn:BasicHttpService/BodyMemberResponse")]
        System.IAsyncResult BeginBodyMember(TestApplication.LegacyBasicHttpServiceReference.BodyMemberRequestMessage request, System.AsyncCallback callback, object asyncState);
        
        TestApplication.LegacyBasicHttpServiceReference.BodyMemberResponseMessage EndBodyMember(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BodyMemberRequestMessage", WrapperNamespace="", IsWrapped=true)]
    public partial class BodyMemberRequestMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string BodyMemberRequest;
        
        public BodyMemberRequestMessage() {
        }
        
        public BodyMemberRequestMessage(string BodyMemberRequest) {
            this.BodyMemberRequest = BodyMemberRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BodyMemberResponseMessage", WrapperNamespace="", IsWrapped=true)]
    public partial class BodyMemberResponseMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string BodyMemberResponse;
        
        public BodyMemberResponseMessage() {
        }
        
        public BodyMemberResponseMessage(string BodyMemberResponse) {
            this.BodyMemberResponse = BodyMemberResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BasicHttpServiceChannel : TestApplication.LegacyBasicHttpServiceReference.BasicHttpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EchoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BodyMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BodyMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicHttpServiceClient : System.ServiceModel.ClientBase<TestApplication.LegacyBasicHttpServiceReference.BasicHttpService>, TestApplication.LegacyBasicHttpServiceReference.BasicHttpService {
        
        private BeginOperationDelegate onBeginEchoDelegate;
        
        private EndOperationDelegate onEndEchoDelegate;
        
        private System.Threading.SendOrPostCallback onEchoCompletedDelegate;
        
        private BeginOperationDelegate onBeginBodyMemberDelegate;
        
        private EndOperationDelegate onEndBodyMemberDelegate;
        
        private System.Threading.SendOrPostCallback onBodyMemberCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public BasicHttpServiceClient() {
        }
        
        public BasicHttpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicHttpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicHttpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicHttpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<EchoCompletedEventArgs> EchoCompleted;
        
        public event System.EventHandler<BodyMemberCompletedEventArgs> BodyMemberCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestApplication.LegacyBasicHttpServiceReference.BasicHttpService.BeginEcho(string message, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEcho(message, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string TestApplication.LegacyBasicHttpServiceReference.BasicHttpService.EndEcho(System.IAsyncResult result) {
            return base.Channel.EndEcho(result);
        }
        
        private System.IAsyncResult OnBeginEcho(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string message = ((string)(inValues[0]));
            return ((TestApplication.LegacyBasicHttpServiceReference.BasicHttpService)(this)).BeginEcho(message, callback, asyncState);
        }
        
        private object[] OnEndEcho(System.IAsyncResult result) {
            string retVal = ((TestApplication.LegacyBasicHttpServiceReference.BasicHttpService)(this)).EndEcho(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEchoCompleted(object state) {
            if ((this.EchoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EchoCompleted(this, new EchoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EchoAsync(string message) {
            this.EchoAsync(message, null);
        }
        
        public void EchoAsync(string message, object userState) {
            if ((this.onBeginEchoDelegate == null)) {
                this.onBeginEchoDelegate = new BeginOperationDelegate(this.OnBeginEcho);
            }
            if ((this.onEndEchoDelegate == null)) {
                this.onEndEchoDelegate = new EndOperationDelegate(this.OnEndEcho);
            }
            if ((this.onEchoCompletedDelegate == null)) {
                this.onEchoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEchoCompleted);
            }
            base.InvokeAsync(this.onBeginEchoDelegate, new object[] {
                        message}, this.onEndEchoDelegate, this.onEchoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestApplication.LegacyBasicHttpServiceReference.BasicHttpService.BeginBodyMember(TestApplication.LegacyBasicHttpServiceReference.BodyMemberRequestMessage request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBodyMember(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginBodyMember(string BodyMemberRequest, System.AsyncCallback callback, object asyncState) {
            TestApplication.LegacyBasicHttpServiceReference.BodyMemberRequestMessage inValue = new TestApplication.LegacyBasicHttpServiceReference.BodyMemberRequestMessage();
            inValue.BodyMemberRequest = BodyMemberRequest;
            return ((TestApplication.LegacyBasicHttpServiceReference.BasicHttpService)(this)).BeginBodyMember(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestApplication.LegacyBasicHttpServiceReference.BodyMemberResponseMessage TestApplication.LegacyBasicHttpServiceReference.BasicHttpService.EndBodyMember(System.IAsyncResult result) {
            return base.Channel.EndBodyMember(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndBodyMember(System.IAsyncResult result) {
            TestApplication.LegacyBasicHttpServiceReference.BodyMemberResponseMessage retVal = ((TestApplication.LegacyBasicHttpServiceReference.BasicHttpService)(this)).EndBodyMember(result);
            return retVal.BodyMemberResponse;
        }
        
        private System.IAsyncResult OnBeginBodyMember(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string BodyMemberRequest = ((string)(inValues[0]));
            return this.BeginBodyMember(BodyMemberRequest, callback, asyncState);
        }
        
        private object[] OnEndBodyMember(System.IAsyncResult result) {
            string retVal = this.EndBodyMember(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBodyMemberCompleted(object state) {
            if ((this.BodyMemberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BodyMemberCompleted(this, new BodyMemberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BodyMemberAsync(string BodyMemberRequest) {
            this.BodyMemberAsync(BodyMemberRequest, null);
        }
        
        public void BodyMemberAsync(string BodyMemberRequest, object userState) {
            if ((this.onBeginBodyMemberDelegate == null)) {
                this.onBeginBodyMemberDelegate = new BeginOperationDelegate(this.OnBeginBodyMember);
            }
            if ((this.onEndBodyMemberDelegate == null)) {
                this.onEndBodyMemberDelegate = new EndOperationDelegate(this.OnEndBodyMember);
            }
            if ((this.onBodyMemberCompletedDelegate == null)) {
                this.onBodyMemberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBodyMemberCompleted);
            }
            base.InvokeAsync(this.onBeginBodyMemberDelegate, new object[] {
                        BodyMemberRequest}, this.onEndBodyMemberDelegate, this.onBodyMemberCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TestApplication.LegacyBasicHttpServiceReference.BasicHttpService CreateChannel() {
            return new BasicHttpServiceClientChannel(this);
        }
        
        private class BasicHttpServiceClientChannel : ChannelBase<TestApplication.LegacyBasicHttpServiceReference.BasicHttpService>, TestApplication.LegacyBasicHttpServiceReference.BasicHttpService {
            
            public BasicHttpServiceClientChannel(System.ServiceModel.ClientBase<TestApplication.LegacyBasicHttpServiceReference.BasicHttpService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginEcho(string message, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = message;
                System.IAsyncResult _result = base.BeginInvoke("Echo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndEcho(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Echo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBodyMember(TestApplication.LegacyBasicHttpServiceReference.BodyMemberRequestMessage request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("BodyMember", _args, callback, asyncState);
                return _result;
            }
            
            public TestApplication.LegacyBasicHttpServiceReference.BodyMemberResponseMessage EndBodyMember(System.IAsyncResult result) {
                object[] _args = new object[0];
                TestApplication.LegacyBasicHttpServiceReference.BodyMemberResponseMessage _result = ((TestApplication.LegacyBasicHttpServiceReference.BodyMemberResponseMessage)(base.EndInvoke("BodyMember", _args, result)));
                return _result;
            }
        }
    }
}
