//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSilver.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtime.OpenSilver.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation..
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SelectedDates collection can be changed only in a multiple selection mode. Use the SelectedDate in a single selection mode..
        /// </summary>
        internal static string Calendar_CheckSelectionMode_InvalidOperation {
            get {
                return ResourceManager.GetString("Calendar_CheckSelectionMode_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next button.
        /// </summary>
        internal static string Calendar_NextButtonName {
            get {
                return ResourceManager.GetString("Calendar_NextButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayMode value is not valid..
        /// </summary>
        internal static string Calendar_OnDisplayModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnDisplayModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstDayOfWeek value is not valid..
        /// </summary>
        internal static string Calendar_OnFirstDayOfWeekChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnFirstDayOfWeekChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SelectedDate property cannot be set when the selection mode is None..
        /// </summary>
        internal static string Calendar_OnSelectedDateChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("Calendar_OnSelectedDateChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedDate value is not valid..
        /// </summary>
        internal static string Calendar_OnSelectedDateChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnSelectedDateChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectionMode value is not valid..
        /// </summary>
        internal static string Calendar_OnSelectionModeChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnSelectionModeChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous button.
        /// </summary>
        internal static string Calendar_PreviousButtonName {
            get {
                return ResourceManager.GetString("Calendar_PreviousButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid..
        /// </summary>
        internal static string Calendar_UnSelectableDates {
            get {
                return ResourceManager.GetString("Calendar_UnSelectableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackout Day - {0}.
        /// </summary>
        internal static string CalendarAutomationPeer_BlackoutDayHelpText {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_BlackoutDayHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar button.
        /// </summary>
        internal static string CalendarAutomationPeer_CalendarButtonLocalizedControlType {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_CalendarButtonLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day button.
        /// </summary>
        internal static string CalendarAutomationPeer_DayButtonLocalizedControlType {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_DayButtonLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decade.
        /// </summary>
        internal static string CalendarAutomationPeer_DecadeMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_DecadeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string CalendarAutomationPeer_MonthMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_MonthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string CalendarAutomationPeer_YearMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_YearMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of Collection does not support changes to its SourceCollection from a thread different from the Dispatcher thread..
        /// </summary>
        internal static string CalendarCollection_MultiThreadedCollectionChangeNotSupported {
            get {
                return ResourceManager.GetString("CalendarCollection_MultiThreadedCollectionChangeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call Show() on a ChildWindow that is in the visual tree. ChildWindow should be the top-most element in the .xaml file..
        /// </summary>
        internal static string ChildWindow_InvalidOperation {
            get {
                return ResourceManager.GetString("ChildWindow_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Calendar.
        /// </summary>
        internal static string DatePicker_DropDownButtonName {
            get {
                return ResourceManager.GetString("DatePicker_DropDownButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatePickerFormat value is not valid..
        /// </summary>
        internal static string DatePicker_OnSelectedDateFormatChanged_InvalidValue {
            get {
                return ResourceManager.GetString("DatePicker_OnSelectedDateFormatChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string DatePicker_WatermarkText {
            get {
                return ResourceManager.GetString("DatePicker_WatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date picker.
        /// </summary>
        internal static string DatePickerAutomationPeer_LocalizedControlType {
            get {
                return ResourceManager.GetString("DatePickerAutomationPeer_LocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Throw Null Exception.
        /// </summary>
        internal static string DatePickerDateValidationErrorEventArgs_ThrowException_NoException {
            get {
                return ResourceManager.GetString("DatePickerDateValidationErrorEventArgs_ThrowException_NoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;enter text here&gt;.
        /// </summary>
        internal static string DatePickerTextBox_DefaultWatermarkText {
            get {
                return ResourceManager.GetString("DatePickerTextBox_DefaultWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template part {0} is not an instance of {1}..
        /// </summary>
        internal static string DatePickerTextBox_TemplatePartIsOfIncorrectType {
            get {
                return ResourceManager.GetString("DatePickerTextBox_TemplatePartIsOfIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime value is in the wrong format..
        /// </summary>
        internal static string DateTimeTypeConverter_FormatException {
            get {
                return ResourceManager.GetString("DateTimeTypeConverter_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstructorParameters cannot be changed because ObjectDataProvider is using a user-assigned ObjectInstance..
        /// </summary>
        internal static string ParameterCollection_EnsureCanChangeCollection_IsReadOnly {
            get {
                return ResourceManager.GetString("ParameterCollection_EnsureCanChangeCollection_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elementName should not be empty..
        /// </summary>
        internal static string ResolveElementNameEventArgs_ctor_ElementNameEmpty {
            get {
                return ResourceManager.GetString("ResolveElementNameEventArgs_ctor_ElementNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RoutedPropertyChangingEvent cannot be canceled!.
        /// </summary>
        internal static string RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation {
            get {
                return ResourceManager.GetString("RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast object of type &apos;{0}&apos; to type &apos;System.Windows.Controls.TabItem&apos;..
        /// </summary>
        internal static string TabControl_InvalidChild {
            get {
                return ResourceManager.GetString("TabControl_InvalidChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for property &apos;SelectedIndex&apos;.
        /// </summary>
        internal static string TabControl_InvalidIndex {
            get {
                return ResourceManager.GetString("TabControl_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property SelectedItem..
        /// </summary>
        internal static string TreeView_OnSelectedItemPropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("TreeView_OnSelectedItemPropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property SelectedValue..
        /// </summary>
        internal static string TreeView_OnSelectedValuePropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("TreeView_OnSelectedValuePropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property HasItems..
        /// </summary>
        internal static string TreeViewItem_OnHasItemsPropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("TreeViewItem_OnHasItemsPropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property IsSelectionActive..
        /// </summary>
        internal static string TreeViewItem_OnIsSelectionActivePropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("TreeViewItem_OnIsSelectionActivePropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot convert from &apos;{1}&apos;..
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
    }
}
