//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSilver.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modification made to the collection lead to an invalid Selection state. Please check the SelectionMode to allow zero or multiple items..
        /// </summary>
        internal static string Accordion_InvalidManipulationOfSelectionCollections {
            get {
                return ResourceManager.GetString("Accordion_InvalidManipulationOfSelectionCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not signal a finish when item is not expected to perform an action..
        /// </summary>
        internal static string Accordion_OnActionFinish_InvalidFinish {
            get {
                return ResourceManager.GetString("Accordion_OnActionFinish_InvalidFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property SelectedIndices..
        /// </summary>
        internal static string Accordion_OnSelectedIndicesChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedIndicesChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property SelectedItems..
        /// </summary>
        internal static string Accordion_OnSelectedItemsChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedItemsChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SelectionMode value &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_OnSelectionModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SelectionSequence value &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_OnSelectionSequencepropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionSequencepropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported collection action &apos;{0}&apos;..
        /// </summary>
        internal static string Accordion_UnsupportedCollectionAction {
            get {
                return ResourceManager.GetString("Accordion_UnsupportedCollectionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentTargetSize is a read-only value and is set through Accordion..
        /// </summary>
        internal static string AccordionItem_InvalidWriteToContentTargetSize {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToContentTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpandDirection is a read-only value and is set through Accordion..
        /// </summary>
        internal static string AccordionItem_InvalidWriteToExpandDirection {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToExpandDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify the IsSelected property while item is locked..
        /// </summary>
        internal static string AccordionItem_OnIsSelectedPropertyChanged_InvalidChange {
            get {
                return ResourceManager.GetString("AccordionItem_OnIsSelectedPropertyChanged_InvalidChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action &apos;{0}&apos;..
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidAction {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start an action when there is no action scheduled..
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidCall {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation..
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition &apos;{0}&apos; was not defined..
        /// </summary>
        internal static string TransitioningContentControl_TransitionNotFound {
            get {
                return ResourceManager.GetString("TransitioningContentControl_TransitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsTransitioning property is read-only..
        /// </summary>
        internal static string TransitiotioningContentControl_IsTransitioningReadOnly {
            get {
                return ResourceManager.GetString("TransitiotioningContentControl_IsTransitioningReadOnly", resourceCulture);
            }
        }
    }
}
