<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Maui\Hybrid\Threading\BackgroundThreadSynchronizationContext.cs" Link="Threading\BackgroundThreadSynchronizationContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="3.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Runtime\Runtime\Runtime.OpenSilver.csproj" />
  </ItemGroup>

</Project>
